name: Docker Image CI
on:
  push:
    branches: [ "master", "release/*" ]
  pull_request:
    branches: [ "master", "release/*" ]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build for windows
      run: docker build . --file windows-build.Dockerfile --tag dns-dropper-windows:$(date +%s)

  build-armv7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build for armv7
        run: docker build . --file armv7-build.Dockerfile --tag dns-dropper-armv7:$(date +%s)

  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build for aarch64
        run: docker build . --file aarch64-build.Dockerfile --tag dns-dropper-aarch64:$(date +%s)